<?php

namespace App\Domain\Repositories;

use Doctrine\Common\Collections;

/**
 * VacancyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VacancyRepository extends \Doctrine\ORM\EntityRepository
{
    public function collectionOfElements()
    {
        $queryBuilder = $this->createQueryBuilder('u')
            ->orderBy('u.id', 'ASC');

        $colelction = new Collections\ArrayCollection($queryBuilder->getQuery()->getResult());
        return $colelction;
    }
}
