<?php

namespace App\Domain\Repositories;

/**
 * VacancyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VacancyRepository extends \Doctrine\ORM\EntityRepository
{
}
